### ISSUE TITLE
RD6030

### ISSUE THREAD

**Issue by Nuqvxz** [morgendagen/riden-dongle#43]
You can add RD6030 (id=60301)?

**Comment by morgendagen** [comment]
Hi,

I have created a new release with untested support for the RD6030 (I do not have access to one).

The main issue is that I do not know the correct V, I and P multipliers to use, so I assume they are the same as for most other models (i.e. 100).

Please check that you get the correct values when reading V, I and P. I'd be grateful for feedback so that I can fix any issues and remove the "untested" designation.

**Comment by Nuqvxz** [comment]
Everything works great with RD6030.

**Comment by hrandib** [comment]
Hi @morgendagen,
I use a firmware without RD6030 support on RD6030 and it looks like something is wrong with P value, others are fine.
Output examples:
27.460 V / 23.520 A / 645.850 W
27.480 V / 24.020 A / 4.700 W
27.500 V / 28.030 A / 115.460 W

I'd say there is an overflow somewhere

**Comment by hrandib** [comment]
It means that RD6030 uses more than 1 holding register to keep this value

**Comment by hrandib** [comment]
It should affect all models from RD6012
